# Generated by Django 5.0.7 on 2024-07-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='transcription',
            field=models.TextField(default=''),
        ),
    ]
